### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by ghost** [komacke/cordova-syncFileSystem#1]
Hey,

This isn't a issue, more a query. I'm about to download and install Android SDK and start on the steps of porting my Chrome App to try to make it a Android App using Cordova.

My Chrome App uses chrome.syncFileSystem as a backbone for the app, it does read/write/edit/delete.

The Android app I want to bulid of the Chrome App will check the user-agent and if it is android will only read from the chrome.syncFileSystem

My query is, will this project enable me to let the Android app I create read files from the chrome.syncFileSystem.

Thank you for your time!

**Comment by komacke** [comment]
Hi Tomatosmoothie,

Yup, that's the idea. It will keep data from a chrome-app and a mobile app sync'd through the Chrome Syncable FileSystem in drive for the same app id.

The cordova-syncFileSystem isn't really complete yet. I've gotten sidetracked with other projects for the last few months but do hope to get back to it.

Dave

**Comment by ghost** [comment]
Thank you for replying.

Actually in my search for a method I stumbled upon this Chrome App https://chrome.google.com/webstore/detail/drive-sample/jpabeekbjicamajjcfejnochhmlbpgjh
Which asks for full drive permission but then manages to view the file and folder created by chrome.syncFileSystem

Made me realize, for my use case of only reading from the chrome.syncFileSystem app folder, would be ideal and probably possible on Android as well. The key would not be required as such since the folder name is based on the chrome app id and is constant.

Thanks.
